const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const sandbox={window:{},document:{addEventListener(){}},console,URLSearchParams,Intl,Date,Set,atob};
vm.createContext(sandbox);
for(const file of ['settings.js','stamp.js','receipt.js'])vm.runInContext(fs.readFileSync(__dirname+'/../'+file,'utf8'),sandbox);
const api=sandbox.window.fueltekSettings, settings=api.defaults();
assert.equal(settings.equipment.length,29);
assert.ok(settings.equipment.find(e=>e.name==='Motosierra').accessories.includes('Funda Espada'));
assert.ok(settings.equipment.find(e=>e.name==='Hidrolavadora').accessories.includes('Pistola'));
const custom=api.clean({...settings,equipment:[...settings.equipment,{name:'Barredora',group:'Limpieza',accessories:['Cepillo','Cepillo',''],conditions:['No arranca'],active:true}]});
assert.equal(custom.equipment.at(-1).accessories.length,1);
assert.throws(()=>api.clean({version:2,equipment:[]}),/compatible/);
const order={ot:'10781',clienteNombre:'Cliente de ejemplo',marca:'STIHL',tipoEquipo:'Motosierra',diagnostico:'Primera línea\n\nSegunda línea\n<script>peligro</script>',trabajo:'Revisión\n\nAjuste',valorTrabajo:85000,montoAbonado:30000,estadoPago:'Abonado',accesorios:['Espada','Accesorio antiguo'],documentoTaller:{business:{name:'Nombre histórico'},receiptNote:'Nota histórica'}};
const html=sandbox.window.fueltekReceipt.build(order,settings);
assert.ok(html.includes('Primera línea\n\nSegunda línea\n&lt;script&gt;'));
assert.ok(!html.includes('<script>'));
assert.ok(html.includes('Nombre histórico'));
assert.ok(html.includes('Accesorio antiguo'));
assert.ok(html.includes('$ 55.000'));
assert.ok(html.includes('60 días corridos'));
assert.ok(html.includes('class="receipt-stamp" src="data:image/png;base64,'));
const flagged=sandbox.window.fueltekReceipt.build({...order,documentoTaller:{...order.documentoTaller,storagePolicyVersion:1}},settings);
assert.ok(flagged.includes('60 días corridos'));
assert.ok(!flagged.includes('bodegaje'));
assert.ok(!flagged.includes('1.500'));
assert.ok(fs.readFileSync(__dirname+'/../receipt.css','utf8').includes('size:letter'));
assert.ok(!html.includes('no se responsabiliza'));
assert.ok(fs.readFileSync(__dirname+'/../receipt.css','utf8').includes('white-space:pre-wrap'));
console.log('PASS catálogo y comprobante: familias específicas, opciones personalizadas, campos históricos, accesorios antiguos, saltos de línea, HTML seguro, saldo y cláusula de retiro.');
